### ISSUE TITLE
[Feature Request] Push To F-Droid

### ISSUE THREAD

**Issue by seniorm0ment** [NO-ob/LoliSnatcher_Droid#1]
Suggesting pushing the app onto F-Droid when stable.

**Comment by grravity** [comment]
Any considerations with this?

**Comment by knby0** [comment]
If the dev agrees, a RFP (Request For Packaging) could be opened here: https://gitlab.com/fdroid/rfp/

**Comment by grravity** [comment]
Probably worth leaving this here too: https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by grravity** [comment]
Is this still planned?

**Comment by seniorm0ment** [comment]
Has there been any progress with an F-Droid release?

**Comment by seniorm0ment** [comment]
Glad to see a release onto Izzy's repo, were you going to try for a release on the official repo too? That would be cool, and would get more people to see the app.

Anyways, could you enable changelog for the F-Droid releases?

**Comment by NO-ob** [comment]
> Glad to see a release onto Izzy's repo, were you going to try for a release on the official repo too? That would be cool, and would get more people to see the app.
> 
> Anyways, could you enable changelog for the F-Droid releases?

I have nothing to do with the app being on that repo so youll have to ask Izzy idk

**Comment by seniorm0ment** [comment]
ok

**Comment by seniorm0ment** [comment]
Closed, because it's submitted? Or not happening?
