### ISSUE TITLE
Exorbitantly high battery usage?

### ISSUE THREAD

**Issue by ZutgKcjA** [NO-ob/LoliSnatcher_Droid#102]
I don't know whether I am the only one, I also don't know what might cause this issue, but the battery usage is exorbitantly high. The app uses as much as 10% of my battery per 10 minutes of use, and I don't think that that is normal or intended. Would like to hear whether you are aware or if you could recommend a course of action.

**Comment by NO-ob** [comment]
I'm not sure what could be causing this
