### ISSUE TITLE
[BUG] snatch blank pictures

### ISSUE THREAD

**Issue by Draydorean** [NO-ob/LoliSnatcher_Droid#103]
When I snatch pictures they are downloaded empty. Videos and gifs are downloaded normally.
![Screenshot_20220309-103440_My Files](https://user-images.githubusercontent.com/101246024/157396938-02ce99d7-ee51-44f0-8317-a5dd872aa2c4.jpg)

**Comment by NO-ob** [comment]
what booru?

**Comment by Draydorean** [comment]
> адрес буру?
https://rule34.xyz

**Comment by NANI-SORE** [comment]
xyz requires a special header entry which isn't included when we save files, will fix that in later releases
