### ISSUE TITLE
[Feature request] Replace the LoliSnatcher title with a tab bar.

### ISSUE THREAD

**Issue by camemb3rt** [NO-ob/LoliSnatcher_Droid#106]
What the title says basically.
I would like to suggest replacing the "Lolisnatcher" title on the top bar with a drop-down tab list, as it seems more intuitive than having to go to the sliding menu and changing tabs there.
Additionally, tablet mode could have tabs just like on a regular internet browser instead, considering the larger screen size.
Also, on an unrelated note, I wish the tags on the info section were grouped into categories, just like they are on most boorus, bringing stuff like character and artist names to the top.

There are some other UI changes I would like to suggest but they're minor. If I find the time I'll try mocking up some graphics to showcase them.

Anyways, love the app in general. Thanks.

**Comment by NANI-SORE** [comment]
Added in 2.3
