### ISSUE TITLE
Videos or gif stuck in buffering

### ISSUE THREAD

**Issue by magelmal132** [NO-ob/LoliSnatcher_Droid#107]
No matter what internet connection I have the vids and gifs won't finish buffering but the pics load instantly

**Comment by NANI-SORE** [comment]
Provide which booru and search query you trying to view + your device info

**Comment by magelmal132** [comment]
The booru is rule34.xxx and the search I just used gif and my phone is a one plus 9, but I've also tried with my galaxy tab 6 and the same thing happened

**Comment by NANI-SORE** [comment]
It seems that there is a bug in their api, resulting in broken urls for files.
I reported it in their discord
