### ISSUE TITLE
[Feature Request] Randomize search results for hydrus network

### ISSUE THREAD

**Issue by Paskalo94** [NO-ob/LoliSnatcher_Droid#109]
I would like the option to be able to get randomized search results for hydrus network like we can do it currently for inkbunny

It can't be done with system predicates or with a tag like with inkbunny AFAIK so something relating to the way loli snatcher requests the results to the hydrux API would have to change I suppose?

**Comment by GreenLandisaLie** [comment]
Already requested:
#92
Also, if you know how to clone and build the source with Flutter I can give you a piece of code that contains minor changes to allow choosing sorting options (using tags such as sort:viewtime), and OR search as well - if you want.

**Comment by Paskalo94** [comment]
That'd be great! if you can't publish it here then please send it to my disposable email olev7711@gmail.com
