### ISSUE TITLE
Viewing images from "favourites" does not show translations

### ISSUE THREAD

**Issue by ghost** [NO-ob/LoliSnatcher_Droid#115]
If an image has translations, they can be viewed from booru-specific search, but not from the favourites tab:

https://user-images.githubusercontent.com/64013111/166177432-87324434-b9b8-476e-bbb8-d1c2d3d7d991.mp4

**Comment by NO-ob** [comment]
Yeah favourites only stores tags and image urls. this probably isn't going to change any time soon
