### ISSUE TITLE
[Feature Request] Remember tabs

### ISSUE THREAD

**Issue by NANI-SORE** [NO-ob/LoliSnatcher_Droid#12]
Currently after closing the app all tabs are deleted.
Would be nice if they were saved or we had a history of tabs/searches

**Comment by NO-ob** [comment]
Sure will work on this

**Comment by grravity** [comment]
Yeah if I recall there is also persistency issue with settings pages too if you switch to another app to copy a url, it didn't save stuff you inputted

**Comment by NO-ob** [comment]
> Yeah if I recall there is also persistency issue with settings pages too if you switch to another app to copy a url, it didn't save stuff you inputted

This might be a memory issue if you have a low end device, my tablet i test on unloads everything when switching between apps but not on my phone

**Comment by grravity** [comment]
It's a flagship, LGv40

**Comment by NANI-SORE** [comment]
@NO-ob I sent another pull request, in case you didn't see

**Comment by NO-ob** [comment]
> @NO-ob I sent another pull request, in case you didn't see

I didn't see that lel, thankyou have merged

**Comment by NO-ob** [comment]
Put a new build with your changes on the releases page

**Comment by NANI-SORE** [comment]
@NO-ob ...and another PR with some fixes
