### ISSUE TITLE
[Feature Request] Add Wallhaven.cc support

### ISSUE THREAD

**Issue by Haseyo** [NO-ob/LoliSnatcher_Droid#123]
Wallhaven.cc has API support but doesn't seem to currently work in LS. Requesting support to the app.

**Comment by NANI-SORE** [comment]
I already did wallhaven handler after a request from a friend ~a month ago, I'll test it and will probably add in the next release

**Comment by NANI-SORE** [comment]
Their api is very limited (they don't give tags in search results array), has a very strict rate limits (can't even load tag data for a single page of search results without hitting the limit) and they have no search autocomplete.
So I don't think its worth adding a site with only support for vieweing only images, without tags or any additional info.
