### ISSUE TITLE
Gelbooru doesn't work

### ISSUE THREAD

**Issue by ghost** [NO-ob/LoliSnatcher_Droid#125]
Gelbooru doesn't load anything, it just says "No data loaded, Tap here to retry" on the bottom header

**Comment by NANI-SORE** [comment]
What is the search query?

**Comment by dizzydoo** [comment]
Probably is the default search query of `rating:safe` which was [deprecated a month ago by danbooru](https://danbooru.donmai.us/forum_topics/21277) and [followed by gelbooru](https://gelbooru.com/index.php?page=forum&s=view&id=5646), in favor of `rating:general` and `rating:sensitive`.
Any chance `rating:general` will be auto-filled as the default tag for these boorus in the next update, or will this still be left up to the user?

**Comment by NANI-SORE** [comment]
I will add an auto-replace from safe to general in the next update, won't change the default query though, rating:safe is still widely used on other sites
