### ISSUE TITLE
DioError when using Sankaku

### ISSUE THREAD

**Issue by ghost** [NO-ob/LoliSnatcher_Droid#128]
When loading an image from Sankaku, it throws a DioError. This stops loading and other interactions such as download.
![Screenshot_20220619-181526](https://user-images.githubusercontent.com/106040280/174720760-7e805751-214a-4fdb-ac40-c7cba004ce2b.png)

**Comment by NO-ob** [comment]
I've seen this a few times for 404s, the results still display on the website i dont think theres anything that can be done about it theres no indication in the results from the api that the posts are broken
![image](https://user-images.githubusercontent.com/15161159/176015922-bfdcbc28-05c3-4d8d-88ae-b23c83b20c08.png)
