### ISSUE TITLE
Make tag filters searchable

### ISSUE THREAD

**Issue by User1l0** [NO-ob/LoliSnatcher_Droid#136]

**Comment by NANI-SORE** [comment]
Please explain in more detail.
Do you want to show search modifiers (sort:score, rating:safe, etc...) as search suggestions?
This is already in our plans

**Comment by NANI-SORE** [comment]
Ok, I'll add text filter there.
Just out of curiosity, how many tag filters do you have?

**Comment by NANI-SORE** [comment]
Added in 2.3, also filters are now sorted alphabetically
