### ISSUE TITLE
Realbooru. Nothing loads nor videos nor images.

### ISSUE THREAD

**Issue by GlowScarf** [NO-ob/LoliSnatcher_Droid#145]

**Comment by NO-ob** [comment]
Its working for me are you still having this issue?

**Comment by GlowScarf** [comment]
No. Most of the videos like 90% of them infinite buffering or Dio errors,
same for photos. Tried deleting and adding booru again but problem
still persists.

**Comment by NANI-SORE** [comment]
It's a known issue, their api gives incorrect urls to files .
Should be fixed in next release

**Comment by NANI-SORE** [comment]
Should be fixed in 2.3
