### ISSUE TITLE
[Feature Request] Tag Highlights

### ISSUE THREAD

**Issue by GlowScarf** [NO-ob/LoliSnatcher_Droid#146]
Can you highlight Artist, Series and Character tag. Also pin at top. Will make searching and recognizing content much easier. Thanks in advance.

**Comment by NANI-SORE** [comment]
was already suggested before (and almost ready to release), please search before posting issues

**Comment by GlowScarf** [comment]
I did search but seems I used wrong words. Thanks for the info tho. Can't
wait for it. Keep up the good work!
