### ISSUE TITLE
[Feature request] Hide favorite (probably cached/saved in db) from searches

### ISSUE THREAD

**Issue by ShaoiZW** [NO-ob/LoliSnatcher_Droid#155]
Pretty much what animeboxes implemented a few months ago. It hides already favorited posts from searches. Just like server may have an option/tag to hide already favorited posts of some users, this does it globally and locally based on cached/stored data.

**Comment by NANI-SORE** [comment]
I already implemented that some time ago, will be in the next release

**Comment by weboid123** [comment]
> I already implemented that some time ago, will be in the next release

can u pls tell me when is next release coming?

**Comment by NANI-SORE** [comment]
Added in 2.3, you can find it in "Tag Filters" settings page
