### ISSUE TITLE
[bug] Restoring a backup does not restore tabs

### ISSUE THREAD

**Issue by ShaoiZW** [NO-ob/LoliSnatcher_Droid#156]
Don't know why, but when restoring a backup, tabs are never restored. Simply add any tab, create a backup, remove all the tabs and restore the backup. Tabs won't be restored (but they are included in the backup database).

**Comment by NANI-SORE** [comment]
Oh, I didn't think about running session restore when restoring a backup, will fix that in next release

**Comment by ShaoiZW** [comment]
Well, I was experimenting with a python script that converts backups from Animeboxes to this apps db for restoring. So I wanted to restore pins from animeboxes as tabs here (don't know if this app has something similar other than tabs).
I also found out that favorites won't show up as favorited (with hearts) and can still be added as favorite, thus duplicating them. But that probably was a mistake on my side (maybe invalid booru name or url or something).

**Comment by NANI-SORE** [comment]
Should work now after 2.3 (currently will force an app restart after a db restore, will make a better flow for this and add if user wants to restore tabs or not in a future version)
