### ISSUE TITLE
When (approximately) will the next update come out?? 

### ISSUE THREAD

**Issue by cielnocturne** [NO-ob/LoliSnatcher_Droid#157]

**Comment by seniorm0ment** [comment]
- [x] Curious too, theres been quite a few commits but no releases posted

**Comment by NANI-SORE** [comment]
When it's done™ and when we'll have time/motivation to finish stuff for the release.
Everything is mostly done, just need to do some final fixes and tests, hope we'll finally do a build on this weekend
