### ISSUE TITLE
szurubooru doesn't work

### ISSUE THREAD

**Issue by crameth** [NO-ob/LoliSnatcher_Droid#159]
LoliSnatcher is not working with szurubooru (I'm a new user so I'm not sure if it has worked before).

Looking at their release history, seems like there's an update about 3 months back that may have broke the API access: https://github.com/rr-/szurubooru/releases/tag/2.5

This is what I see on my szurubooru API; LoliSnatcher successfully accesses the API with response 200:
```
172.19.0.9 -> GET /api/posts/?offset=0&limit=5&query=* HTTP/1.1 [200] - referer: - 192.168.1.12
```

However LoliSnatcher thinks the API isn't working:
<img src="https://user-images.githubusercontent.com/2794843/193646201-9cbf4cdd-a10c-4c0e-a394-0659e182a7ab.png" width="400" />

I can access and use szurubooru normally.

**Comment by NO-ob** [comment]
What booru?

**Comment by crameth** [comment]
@NO-ob It's my own self-hosted szurubooru instance.

**Comment by crameth** [comment]
Hi! Just wanted to update that the latest bunch of fixes resolved this issue for me.

Closing this. Thanks!
