### ISSUE TITLE
Szurubooru engine: Board found

### ISSUE THREAD

**Issue by Oreloth** [NO-ob/LoliSnatcher_Droid#161]
@NO-ob
Just found a board using Szurubooru, as requested in [README.md](https://github.com/NO-ob/LoliSnatcher_Droid/commit/7c60648cee7ff922f97f96d0e7455b1e34fad096) so there it is: [https://infinibooru.moe/](https://infinibooru.moe/)

**Comment by NO-ob** [comment]
Thanks
