### ISSUE TITLE
Tag suggestions broken for tags that include ' or similar characters

### ISSUE THREAD

**Issue by Vendicated** [NO-ob/LoliSnatcher_Droid#164]
for example Ina's tag `ninomae_ina'nis ` on gelbooru.
It is displayed as html encoded value `ninomae_ina&#39;nis`. Choosing this suggestion in the search bar leads to 0 results. Manually changing it to ' fixes i 

(I was gonna try to open a PR to fix it, but #163 stopped me)

**Comment by coolst3r** [comment]
This appears to be an issue with the way the tag is encoded on the website. The HTML encoding of the apostrophe character is causing the search to fail. Manually changing the encoded value to the apostrophe character in the search bar resolves the issue. However, opening a PR to fix the underlying issue may be necessary to ensure that the search works properly for other users in the future.

**Comment by NANI-SORE** [comment]
Was probably fixed in 2.3.2, but please comment if it still happens now

**Comment by Vendicated** [comment]
Seems fixed, thank you!
