### ISSUE TITLE
Can no longer exclude tags in favorites search

### ISSUE THREAD

**Issue by Kerobyte** [NO-ob/LoliSnatcher_Droid#168]
![Screenshot_20221121-195640](https://user-images.githubusercontent.com/55901764/203151198-7476434d-9e81-46f4-b9f8-2d5f6802087c.png)
![Screenshot_20221121-195327](https://user-images.githubusercontent.com/55901764/203151207-1e401238-9d36-4d3b-ba04-5cb0ed9270c2.png)

**Comment by NANI-SORE** [comment]
Fixed in 2.4.0, sorry it took so long, I forgot about many of the issues when I was doing other releases
