### ISSUE TITLE
Danbooru stopped working after update

### ISSUE THREAD

**Issue by Wasuregusa** [NO-ob/LoliSnatcher_Droid#170]
I recently updated to 2.3.0 from 2.2.5 and the app suddenly became unable to connect to [danbooru.donmai.us](danbooru.donmai.us), getting stuck trying to load a page.

I removed the booru from the list and tried to add it again, thinking that maybe the config data from the previous version wasn't entirely compatible with the newer one, but then the procedure failed in the "Test Booru" step with a "no data returned" error. I tried several other stuff for a bit, but it didn't pan out so I ended up reverting back to 2.2.5.

**Comment by NANI-SORE** [comment]
Was there any error code at the end of "No data returned" message? If it says 401, try adding your api key
There is a bug with credentials on danbooru parser right now, we'll try to release a fixed build on the weekends

**Comment by Wasuregusa** [comment]
Specifying the API key worked! Thanks for the prompt reply!
