### ISSUE TITLE
e621 not working anymore

### ISSUE THREAD

**Issue by sys32n-1** [NO-ob/LoliSnatcher_Droid#173]
the app shows an error (503) when i try to join e621. when you try to test the booru it appears the same error

**Comment by Redactx** [comment]
Having the same issue! I hope this gets resolved soon.

**Comment by NO-ob** [comment]
They were being ddosed apparently cloudflare is disabled now i think

**Comment by KoleckOLP** [comment]
yeah it seems to work again

**Comment by sys32n-1** [comment]
ye its working now!

Em qua., 14 de dez. de 2022 10:53, koleq ***@***.***>
escreveu:
