### ISSUE TITLE
[Site Request] Wildcritters

### ISSUE THREAD

**Issue by AppleCanon** [NO-ob/LoliSnatcher_Droid#174]
Apologies, im not sure if its possible but would implementing access to wildcritters.ws be possible? Im not sure if its actually a booru or not but it has a similar layout, at least to me it does. Then there's the "Archive" section of the old site.

**Comment by AppleCanon** [comment]
I guess "imageboard" would fit better but idk

**Comment by NO-ob** [comment]
Support will be in next version its a bit slow though
