### ISSUE TITLE
Danbooru now returns 403 errors

### ISSUE THREAD

**Issue by Wasuregusa** [NO-ob/LoliSnatcher_Droid#185]
Today the app suddenly stopped working with site danbooru.donmai.us with an `Error happened when loading page #1 http status error 403` message.

I was running version 2.3.0, so I tried upgrading to 2.3.1 to no avail. I tried both versions with and without setting up the API key, but all combinations failed.

Finally, I rolled back to version 2.1.5 just because I happened to have the apk file for it in the downloads folder since who knows when, and to my surprise that DID work without having to set up the API key. Next I tried installing versions 2.2.0 and 2.2.5, and they worked too.

I suspect the site suddenly changed something and that ended up relaxing their restrictions to interact with the API, but whatever it was that also made versions 2.3.0 and 2.3.1 fail to retrieve proper responses from the site.

**Comment by dizzydoo** [comment]
Just to add to this, on v2.3.1 and noticed this happening too despite having ID, API key and session cookies saved. With logging enabled, Alice inspector shows that it hits a Cloudflare challenge/bot check page during the GET requests for posts.

**Comment by kyoyacchi** [comment]
![Screenshot_20230222-132057](https://user-images.githubusercontent.com/63583961/220592060-722208d8-83c5-4572-8549-e4d99cacb04d.jpg)
Working for me (ver 2.3.2). Try using VPN? I'm using ProtonVPN since these kind of websites are blocked in my country.

**Comment by NANI-SORE** [comment]
Fixed in 2.3.2
It happened because danbooru now doesn't allow api requests with browser user agents

**Comment by kyoyacchi** [comment]
> Fixed in 2.3.2 It happened because danbooru now doesn't allow api requests with browser user agents

I see

**Comment by Wasuregusa** [comment]
Can confirm it's fixed in v2.3.2.
