### ISSUE TITLE
Asking for Captcha, but there are none!

### ISSUE THREAD

**Issue by SquareUsEnix** [NO-ob/LoliSnatcher_Droid#188]
Danbooru
Pixivel and probably much more!

Those 2 are they only 2 i know so far, where you need to solve a Captcha, but there is no Captcha.

This did not happen before, so i wonder what should be done about that.

I tried to use User ID and API Key but that did not change anything.

I use the Version 2.3.2 from PlayStore

**Comment by NANI-SORE** [comment]
That's a new feature added in 2.3.2 we are testing now.
Danbooru should work fine, try entering your login in "user id" instead of id (if that's what you had there before), I forgot to rename that field for danbooru.
Never heard of pixivel before, what engine is that using?

**Comment by SquareUsEnix** [comment]
I searched for Booru Websites here: https://gist.github.com/lxfly2000/c183fcd23cfb447b2b9cb353e103c8fe

And tried Pixiv but nothing happened so i tried out Pixivel but then i got a message about a Captcha that was not even there.

For Danbooru it doesnt matter what i do, it still asks me about Captchas that are not even there.

**Comment by vicclln** [comment]
I was also faced this issue with Danbooru. Try to type your Username instead of ID, then add your API key. Then log in your account in test. It would still ask for captcha, but eventually as you press back multiply times, it'll display that you can save this booru.

**Comment by NANI-SORE** [comment]
Fixed wrong field name for Danbooru that caused confusion in 2.3.3
Using User ID instead of Login causes Danbooru to deny requests
