### ISSUE TITLE
Got handed a warning on the repo now, please appeal that ASAP

### ISSUE THREAD

**Issue by TheK0tYaRa** [NO-ob/LoliSnatcher_Droid#189]
![image](https://user-images.githubusercontent.com/27967034/221371783-9e9c48a1-609a-4cd6-a71a-c321298fb2f3.png)

**Comment by NO-ob** [comment]
Thanks

**Comment by averne** [comment]
It's over

**Comment by yokiyoki22** [comment]
By this logic they need to flag all web browsers too, you could search for explicit content!

**Comment by NO-ob** [comment]
> By this logic they need to flag all web browsers too, you could search for explicit content!

Yeah i said that in the appeal it doesn't make sense why they've added the warning

**Comment by NANI-SORE** [comment]
It's not over, anon users still can't access the repo

**Comment by SeranaX** [comment]
Warning still appears. 
Most likely related to the pictures in the README.

**Comment by TheK0tYaRa** [comment]
why ._.

**Comment by Katzenwerfer** [comment]
Although not ideal, a mirror of the repo into a different git hoster could works as a temporal workaround.

**Comment by TheK0tYaRa** [comment]
I suggest gitgud.io
