### ISSUE TITLE
Add socks5 proxy with dns over proxy enabled webrtc disabled and canvas fingerprint randomized option support for apps like orbot, add lolibooru.moe   booru.allthefallen.moe   qoh.booru.org  futabooru.booru.org  rule34.xxx  tbib.org  and 9hentai.ru support

### ISSUE THREAD

**Issue by User1l0** [NO-ob/LoliSnatcher_Droid#19]

**Comment by NO-ob** [comment]
>Add socks5 proxy with dns over proxy enabled webrtc disabled and canvas fingerprint randomized option support for apps like orbot
What

Most of these booru are already supported. Booru.org has no api because they use an old gelbooru version so not sure if ill add support for that scraping their sites is slow.
