### ISSUE TITLE
Realbooru not loading

### ISSUE THREAD

**Issue by SquareUsEnix** [NO-ob/LoliSnatcher_Droid#191]
On Version 2.3.2 when i try Realbooru it sometimes loads Images and sometimes not.

It never loads Videos.

I get the Error: Loading Error: Http status error [404].

I tried only using Realbooru Multibooru, reinstalling and even deleting everything and only using Realbooru with Standard Settings, nothing works.

**Comment by NANI-SORE** [comment]
Fixed in 2.3.3, but now every image/video has to go through process of elimination with extra requests to server to decide which file extension to use, that's why you'll see a question mark on thumbnails for some items
