### ISSUE TITLE
Share to hydrus sends direct image url in all cases

### ISSUE THREAD

**Issue by crazybmanp** [NO-ob/LoliSnatcher_Droid#194]
When sending an image to Hydrus to download the application always sends a direct link to the image, however Hydrus can handle being given gallery URLs of most galleries and do more in-depth scanning of tags and the page.

Unfortunately this will not work if your Hydrus instance doesn't have a downloader for that page, as instead it will need the link directly to the image. However, It would be nice if users of that feature could specify certain boorus to send webpage urls of.

**Comment by NANI-SORE** [comment]
Added a dialog in 2.4.0, which will ask what to share to hydrus
