### ISSUE TITLE
rule34hentai.net is not working

### ISSUE THREAD

**Issue by someshittyeletronicmusicband** [NO-ob/LoliSnatcher_Droid#195]
It just shows a bunch of HTTP 403 errors

**Comment by NANI-SORE** [comment]
Works fine for me. Did you use US vpn? That's their requirement to access the site

**Comment by NANI-SORE** [comment]
Oh and if you are trying to add it with autodetect, just select r34hentai booru type, autodetect is a bit broken in the current version and will spam webviews on every invalid test request. That's a known issue which will be fixed later

**Comment by someshittyeletronicmusicband** [comment]
Do you really need a VPN? The website itself works just fine here, be it on mobile or PC.

![new](https://user-images.githubusercontent.com/89416947/225982142-404decff-8b31-4a4b-8ec5-e94e172857da.png)

**Comment by NANI-SORE** [comment]
@someshittyeletronicmusicband
Do you use this site often outside the app? How often does cloudflare check last for you?
In my tests it feels like it expires after ~10-20 minutes, but maybe that's because I use VPN

**Comment by NANI-SORE** [comment]
Should work better in 2.3.3, all requests now use cookies from webview that allows you to pass cloudlfare check
