### ISSUE TITLE
Default tags for individual boorus don't work

### ISSUE THREAD

**Issue by SleepzCat** [NO-ob/LoliSnatcher_Droid#205]
When trying to set the default tags in each individual booru listing, it never applies to any new tabs, it seems to be overridden by the main default tag option. For example I have both Danbooru and Gelbooru set to default tag: rating:general and Sankaku set to default tag: rating:safe, but no matter what they never apply, even when the main default is set to nothing.

**Comment by NO-ob** [comment]
Are you hitting test and then save after setting the tag? it wont set if you just exit

**Comment by NANI-SORE** [comment]
Fixed in 2.3.3
