### ISSUE TITLE
Multiple compile errors

### ISSUE THREAD

**Issue by drwankingstein** [NO-ob/LoliSnatcher_Droid#208]
1. Dio dio replaced assureDioError: fixed with 
`sed -i 's/assureDioError/assureDioException/g' lib/src/utils/dio_network.dart`

2. Getting a photoview issue
```
ERROR: ../../../.pub-cache/git/photo_view-e1efd408a788d497ef76a6ab755c648cc93e9380/lib/src/core/photo_view_gesture_detector.dart:89:38: Error: No named parameter with the name 'kind'.
ERROR:   }) : super(debugOwner: debugOwner, kind: kind);
ERROR:                                      ^^^^
ERROR: Target kernel_snapshot failed: Exception
```
removing it seems to work but it seems like the proper solution is to 
`to replace kind: kind` with  `supportedDevices: kind != null ? {kind} : null`

**Comment by NANI-SORE** [comment]
Both should be fixed in the current branch
