### ISSUE TITLE
Client API accessible via web browser but not through client

### ISSUE THREAD

**Issue by Molanoll** [NO-ob/LoliSnatcher_Droid#21]
While setting up Hydrus, I was able to get the API key through a request, but it is not able to pass the test. I am also able to view the welcome page to the client api on my mobile web browser. If the welcome page is viewable, shouldn't it also be possible to verify the access key or whatever the test is doing? It seems to hang for a while after I click the test button, like it times out maybe. Not sure what the cause of this is. Any ideas?

**Comment by NO-ob** [comment]
Not sure what could be causing it ill make a test apk for you in a couple hours so I can get some more info

**Comment by NO-ob** [comment]
Install the attached apk
[app-release.zip](https://github.com/NO-ob/LoliSnatcher_Droid/files/5875485/app-release.zip)

You will need to enable android debugging on your phone also

Open the app and go to the page to add the booru, fill in the information for hydrus and get the api key

before hitting test open the terminal on your computer and run adb logcat | grep flutter > log.txt

then hit test and wait for it to say no data is found then ctrl+c on the terminal and put the log here

**Comment by Molanoll** [comment]
[out.txt](https://github.com/NO-ob/LoliSnatcher_Droid/files/5876106/out.txt)

There it is. Grep was not working on the log file for some reason, but it did seem to work on different files. Anyways, I went through and manually got all "flutter" lines, so this file should still be accurate.

**Comment by NO-ob** [comment]
I think it wasn't working because you have untagged files in your hydrus, try this it should fix it
[app-release.zip](https://github.com/NO-ob/LoliSnatcher_Droid/files/5876270/app-release.zip)

**Comment by Molanoll** [comment]
It seems to work now.
