### ISSUE TITLE
No gifs and images are low resolution

### ISSUE THREAD

**Issue by Kimarnic** [NO-ob/LoliSnatcher_Droid#215]
This new update 2.3.3 broke everything, gifs won't play and images show up ultra blurry when in Gelbooru they're fine.
This didn't happen until the update.
Downgrading to 2.3.2 and everything works fine, please fix!

**Comment by NANI-SORE** [comment]
Are you using the sample quality in gallery? In 2.3.2 that setting was accidentally ignored and full quality images loaded instead.
On which sites this happens? It's possible that either we set up sample urls wrong for them or their api gives incorrect data

**Comment by Kimarnic** [comment]
You were right about the sample thing, now everything works again

**Comment by NANI-SORE** [comment]
I would still like to know on which boorus you had bad sample images

**Comment by Kimarnic** [comment]
Sure! I only use Gelbooru
