### ISSUE TITLE
Can't find favorited tags in database file

### ISSUE THREAD

**Issue by Endferoma** [NO-ob/LoliSnatcher_Droid#221]
Really love the program so far.. 
I was trying to extract my favourited tags, but I can't find them. I was thinking it's saved in the store.db file, but there I only see favorited pictures, not tags. Where are they, can you help? :)

**Comment by NANI-SORE** [comment]
They are in settings json in lovedTags

**Comment by Endferoma** [comment]
thank you, indeed it's there ^.^
