### ISSUE TITLE
Send Post URLs to hydrus, not Image/CDN Links

### ISSUE THREAD

**Issue by Ryonez** [NO-ob/LoliSnatcher_Droid#222]
I've noticed that when you add a hydrus client to the boorus, you get an option to share an image to the hydrus client.

However, the direct image URLs are used instead of the post ones you'd see if you where to use "Open in Browser". I'm guessing this also means the tags are being sent from lolisnatcher as well.

I'd like to see this replaced, or an option added to send the hydrus client the post urls (just the post URL's, no need to send tags), which would let hydrus run them through it's parsers. This would mean, if the parser is set up, that all the urls on the post would be added (not just the cdn/image link), notes/descriptions, etc.

**Comment by NANI-SORE** [comment]
Added a dialog in 2.4.0, which will ask what to share to hydrus
