### ISSUE TITLE
[Question] What does "~" search modifier do?

### ISSUE THREAD

**Issue by Leo-Aqua** [NO-ob/LoliSnatcher_Droid#229]
I know that "-" removes a tag from a search but what does "~" do?

**Comment by KnockoffFeline** [comment]
From Danbooru's [cheat sheet](https://danbooru.donmai.us/wiki_pages/help%3Acheatsheet):

> [~blonde_hair ~blue_eyes](https://danbooru.donmai.us/posts?tags=~blonde_hair%20~blue_eyes)
>
>Legacy disjunctive operator, equivalent to [blonde_hair or blue_eyes](https://danbooru.donmai.us/posts?tags=blonde_hair%20or%20blue_eyes).
