### ISSUE TITLE
[Feature Request] Saving to SD Card

### ISSUE THREAD

**Issue by Kaanibaru** [NO-ob/LoliSnatcher_Droid#23]
Would be nice since snatching lots of pictures does fill up internal storage quite well.

Also, the app is great so keep up the awesome work!

**Comment by NO-ob** [comment]
I'll look into doing that, not sure if I can do it for android 11 though

**Comment by baraa272** [comment]
Also how to change folder name where snatched photos downloaded ??

**Comment by NO-ob** [comment]
> Also how to change folder name where snatched photos downloaded ??

you cant at the moment will be available soon

**Comment by NO-ob** [comment]
> Would be nice since snatching lots of pictures does fill up internal storage quite well.
> 
> Also, the app is great so keep up the awesome work!

Do you know what the path for your sdcard is? i've tried two devices with sdcard readers and the both use the path /sdcard/ which i think links to /storage/sdcard0. This is selected by default on the devices and is where images the app stores images so i'm not entirely sure what paths to check for. What android version are you using also

**Comment by Kaanibaru** [comment]
> > Would be nice since snatching lots of pictures does fill up internal storage quite well.
> > Also, the app is great so keep up the awesome work!
> 
> Do you know what the path for your sdcard is? i've tried two devices with sdcard readers and the both use the path /sdcard/ which i think links to /storage/sdcard0. This is selected by default on the devices and is where images the app stores images so i'm not entirely sure what paths to check for. What android version are you using also

The path for my SD Card seems to be /storage/6DF8-18A7, at least that's the only place where I was able to find the files using some root file browser.
My phone is a Poco X3 and I'm running ArrowOS on Android 11.

**Comment by baraa272** [comment]
hope there is an update on this issue
