### ISSUE TITLE
Note positioning is broken

### ISSUE THREAD

**Issue by KnockoffFeline** [NO-ob/LoliSnatcher_Droid#230]
The position and size of notes does not always match up, and it can even go out of bounds.
For an example, search for `id:6832532` on Danbooru, or see this image below.

![Screenshot_2023-11-04-15-58-50-307_com noaisu loliSnatcher](https://github.com/NO-ob/LoliSnatcher_Droid/assets/62443058/081ac2f3-d0f9-4ebc-a041-89b6b1774fc5)

The notes also move every time I double-tap twice to zoom to actual size.
Changing the Gallery Quality setting to "Full Res" _almost_ solves the issue, but not quite.

**Comment by NANI-SORE** [comment]
Should be fixed in 2.4.0
