### ISSUE TITLE
Idol SankakuComplex, No Data Returned, DioException, RedirectException

### ISSUE THREAD

**Issue by NanoAi** [NO-ob/LoliSnatcher_Droid#243]
Trying to use Idol SankakuComplex returns.
```
No Data Returned.
Entered Information may be incorrect, booru doesn't allow api access or there was a network error. Error text:
"DioException [unknown]: null
Error: RedirectException:
Redirect loop detected"
```

Entering the idol sankaku domain, changes it to `iapi.sankakucomplex.com`, opening to grab cookies works. 
This doesn't work even if I try to access it with an account.

**Comment by NANI-SORE** [comment]
Should be fixed in 2.4.0 + you can now properly login into idol now, in previous versions it wasn't implemented
