### ISSUE TITLE
cannot switch boorus after recent update

### ISSUE THREAD

**Issue by ChillHorse** [NO-ob/LoliSnatcher_Droid#29]
After Update I had to reconfigure the application because it couldn't read the previous configs. 

Now when trying to switch boorus and searching, the default Booru will always return the search result.

screenrecording on mega since I didn't bother to compress it https://mega.nz/file/Wg8WzDJQ#qrdKRBAXD6b1nHr9iSRnfzQvQkkczk518gEYCjcml8I

sidenote: the buttons in the about page don't seem to work as well

**Comment by NO-ob** [comment]
Will fix at some point, i'm aware of this and forgot about it i'm pretty sure if you go into settings and change the booru that is selected in the dropdown there and then save settings it will stop doing it

**Comment by NO-ob** [comment]
The buttons not working seems to be an android 11 issue ill fix those for the next update

**Comment by NO-ob** [comment]
Both have been fixed
