### ISSUE TITLE
Save button

### ISSUE THREAD

**Issue by baraa272** [NO-ob/LoliSnatcher_Droid#3]
Hi and thanks for shilling 
But it seems like the app save button not working at all here on my end (S7 edge) 
I tried many many times but the app won't save any newer sites even if it tells me connection was successful

**Comment by grravity** [comment]
Just tested on my device, I do not receive any errors, it says it was saved successfully.
However, I do not see it saved in my Gallery, nor the LoliSnatcher folder. 
Seems like the same issue as your last comment. So can confirm.

Android 10, LGv40
