### ISSUE TITLE
Reporting bugs with gallery view, e621, snatcher and staggered view

### ISSUE THREAD

**Issue by ZutgKcjA** [NO-ob/LoliSnatcher_Droid#31]
Hello, I just wanted to report some bugs with Loli Snatcher: 

- in gallery view, when you reach the last image of a certain page, you cannot simply continue to the first image of the next page. First, you have to go back one image in order to go forward to the next page.
- on e621, in both preview mode and gallery mode, the first page is loaded twice. Meaning that, if you load the first 20 images, you scoll down to the end, and the same 20 images appear again. This happens only on the first page. 
- in the snatcher, tested with e621 and Paheal, at least the top 100 images are downloaded twice for a given tag. I am not aware if the introduction of the database in the latest patch has changed this behavior.
- if you select staggered view in the options (added in the latest patch), Loli Snatcher does not remember the (correct) position in preview mode when you switch into gallery mode (by tapping on an image) and back out again. The app _does_ remember the correct position in waterfall view and has in previous patches. 

Sorry for any mistakes with the formatting of my bug report, I am very new to GitHub.

**Comment by NO-ob** [comment]
For the first i'm aware of this but forgot about it, if you scroll a bit slower on the last 7 images or so it should have time to update before you get to the last one but ill take another look at this at some point

 e621 has been fixed for the 2 middle bugs. I cant reproduce paheal downloading images twice though. Are you on android 11 and do you have the database enabled? If you are on android 11 your file storage cant be checked for the files so duplicates will be downloaded without the database. I did notice though that they use different urls for their files so if these aren't static I will need to fix it but I did a snatch for 200 images on paheal and then repeated and none of them downloaded again.

I'm aware of the thing with staggered grid view aswell

**Comment by ZutgKcjA** [comment]
I guess I'll just wait until the update comes through on Google Play. 
I am on version 1.7.6, I really should have said that before. I can say for sure that on this version, bugs 1, 2 and 4 exist and are not fixed. The suggested workaround for bug 1 does not work, as far as I can tell, because in gallery view, the next page is only loaded once you get the last image of the previous page. 

Unfortunately, I also have a new bug to report. I cannot check on bug 3, the problem I had with the snatcher, because since the update, the snatcher does not work at all for me. It just tells me it's snatching the images and to not close the app, and then nothing happens no matter how long I wait. (tested this with Gelbooru, rule34.xxx, Paheal and e621 and different tags)

**Comment by NO-ob** [comment]
I have pushed a new build to the play store it probably wont be live for a few days because they are slow, you can get the build here but youll have to uninstall the play store version first https://github.com/NO-ob/LoliSnatcher_Droid/releases

if you are on android 11 uninstalling will wipe all your settings so you might wanna wait, you also wont get updates via google play if installing this version
