### ISSUE TITLE
Hydrus Tag List Not In Order

### ISSUE THREAD

**Issue by grravity** [NO-ob/LoliSnatcher_Droid#38]
When going to a media in LoliSnatcher (Hydrus), opening the tags list, it is out of order. Other boorus show up as Alphabetical.

**Comment by ZutgKcjA** [comment]
Would you even want tags to be in alphabetical order? I feel like tags should be seperated by category (such as "artist", "character", "copyright", "general" etc.) to make it easy to find what you are looking for. I always struggle to pick out the artist from an alphabetized tag list.

**Comment by grravity** [comment]
The artist tags are usually creator:, if it was alphabetized all you'd need to scroll to are the creator: tags.
I fail to understand the issue

**Comment by NO-ob** [comment]
Ask the hydrus devs to make their api return ordered tags like every other booru does
