### ISSUE TITLE
Frequent crashes on V1.7.8, due to memory leak?

### ISSUE THREAD

**Issue by ZutgKcjA** [NO-ob/LoliSnatcher_Droid#39]
I get frequent crashes on version 1.7.8 just using the app normally. Browsing as little as 50-100 images in gallery view (where the file sizes tend to be large or very large), my phone heats up, the app starts to lag then hang and it is guaranteed to crash. 
It feels like some kind of memory overflow, and I have found a commit by nani-sore addressing a potential problem with a memory leak. Maybe this is the solution to the problem. 
The commit has not been pushed to the Google Play version yet though, so I cannot tell. I need this update to make the app actually usable again.

**Comment by NANI-SORE** [comment]
Yeah, I messed up the original caching logic which lead to memory leaks. It is fixed in the later commits. I'll ask @NO-ob to release a new build when possible.

**Comment by NO-ob** [comment]
I've pushed a build to the play store, it will be up within 3 days or so
