### ISSUE TITLE
[Feature Request] Changes to the way tags are displayed?

### ISSUE THREAD

**Issue by ZutgKcjA** [NO-ob/LoliSnatcher_Droid#40]
I would love to see some changes to the way an images tags are displayed when you press on the "info"-button. 
Display the tag count (number of pictures with that tag), and color code them by category or even separate by category. Essentially, I'd like to see it look more like tags look on Gelbooru or e621 (examples attached).
![e621](https://user-images.githubusercontent.com/80195255/112349753-49d5de00-8cc9-11eb-8fcd-a50b0a1bf135.png)
![gelbooru](https://user-images.githubusercontent.com/80195255/112349755-4a6e7480-8cc9-11eb-904e-7adf9cdab4f0.png)

**Comment by NO-ob** [comment]
The reason I haven't done this is that only danbooru returns tag types, to do it would require querying the booru apis for every single tag for every image and I think thatd be quite slow

**Comment by ZutgKcjA** [comment]
If you look at your source code for e621, you're already snatching tags by type. I don't know what it's like for other boorus.

**Comment by NO-ob** [comment]
Not all booru engines return tags as types so I don't think using what the apis provide is a good solution

**Comment by NANI-SORE** [comment]
Another way of doing this is creating separate files with tags data scraped from different sites which then users could download and merge with local db of the app. Grabber does something like this for their colored tags.

I already scraped a list of ~60k of tags which have at least 100 images. But I won't start implementing it until I complete rewriting the app's core logic and testing for 2.0

**Comment by NANI-SORE** [comment]
Added in 2.3 for some boorus
