### ISSUE TITLE
Screen turns off when playing videos

### ISSUE THREAD

**Issue by ZutgKcjA** [NO-ob/LoliSnatcher_Droid#41]
When playing a video on Loli Snatcher, the phone screen turns off after some time, due to no input being registered (such as tapping on the screen). While playing a video, the screen should remain forced on, without having to tap on the screen periodically.

**Comment by NANI-SORE** [comment]
It's on my todo list, but not sure when I'll do this. As a temp solution - screen stays on when in fullscreen

**Comment by NO-ob** [comment]
Will be in next update
