### ISSUE TITLE
[Bugs]

### ISSUE THREAD

**Issue by NANI-SORE** [NO-ob/LoliSnatcher_Droid#42]
- sometimes after exiting settings all tabs are forced into default booru (or the booru selector is resetted?)
- text fields are not scrolling into view when keyboard is open (for example apikey/userid in booru edit page)
- sometimes favourited items are not loaded in time, especially on app start (maybe dbhandler is not loaded in time?)

**Comment by grravity** [comment]
Downloading seems to be broken?
If I click save, it says it's queued, then says it's been snatched already.
I look in my gallery and it's not there.
