### ISSUE TITLE
Snatching bug

### ISSUE THREAD

**Issue by flleeppyy** [NO-ob/LoliSnatcher_Droid#46]
Snatching many pictures takes time, so I left the app for a while, came back, and it was at the same number i left the app on. If i leave the app in the foreground instead of switching to another app, it'll continue downloading.

Basically, it only downloads when the app is in focus, not when the phone screen is off or another app is in focus

**Comment by ZutgKcjA** [comment]
This might be the intentional behavior built into Android. With the app going out of focus, it is "paused" to save on energy. Have you tried to exclude Loli Snatcher from your Android Power Management settings and seeing if that changes anything?
