### ISSUE TITLE
[Feature Request] View Multiple Files At Once

### ISSUE THREAD

**Issue by seniorm0ment** [NO-ob/LoliSnatcher_Droid#47]
An odd idea I had was to be able to view multiple files at once. The way I imagine it is the user can select multiple files, then it opens them similar to a tiling wm, no borders, so it fits them like puzzle pieces in the best way to preserve their resolution while minimizing as much blackbars as possible. The user can then add a priority image they want to be biggest.

**Comment by ZutgKcjA** [comment]
I feel like maybe this shouldn't be a priority. I can imagine this looking good on a large tablet screen, but on my small phone I struggle with just one image being displayed at a time. Also, I can't imagine how much work it would be to implement such a feature ultimately purely for aesthetics.
