### ISSUE TITLE
[Feature Request] Hold To Disable All Audio

### ISSUE THREAD

**Issue by seniorm0ment** [NO-ob/LoliSnatcher_Droid#48]
requesting the ability to hold the audio icon on a file, to then disable all upcoming files audio as well. A single click disables just for that file, a hold holds the audio disable.

**Comment by ZutgKcjA** [comment]
Alternatively turn down media volume to zero on Android, using the volume rocker on the side of your phone. (workaround)

**Comment by seniorm0ment** [comment]
that only works if you want to mute all audio, however i realized soon after posting my android version has individual volume control on an app level so I can mute lolisnatcher individually.
that being said, not all devices have this, and it is a bit more work than being able to just hold down the volume mute button in the app. good to have in the app still

**Comment by NO-ob** [comment]
Will be in the next update
