### ISSUE TITLE
[Feature request] Process bar when saving images. 

### ISSUE THREAD

**Issue by cordelia04m** [NO-ob/LoliSnatcher_Droid#5]
Since version 1.6.8 can now select multiple images and save them, but you can't know how much of the task is done (there are modification on the bottom side but they will show up only 1 if multiple images are done donwloadin at the same time.) Adding a process bar or a counter would be a nice QoL improvement.

**Comment by NO-ob** [comment]
I will work on it thankyou

**Comment by generoberts** [comment]
Thanks you.

**Comment by NO-ob** [comment]
Not a progress bar but ive added a counter to the top of the app where it normally says loli snatcher it will be available in the next update, heres a build with the changes if you wanna try it out I haven't done much testing on it yet though
[app-release.zip](https://github.com/NO-ob/LoliSnatcher_Droid/files/5898867/app-release.zip)
