### ISSUE TITLE
Philomena User-Defined Filters Overridden

### ISSUE THREAD

**Issue by GoAwayNow** [NO-ob/LoliSnatcher_Droid#51]
When an authenticated user makes an API request on a Philomena booru, the user's defined default filter is used unless overridden in the request.

Because Loli Snatcher includes [a static filter id](https://github.com/NO-ob/LoliSnatcher_Droid/blob/master/lib/libBooru/PhilomenaHandler.dart#L107) for both unauthenticated and authenticated users, user-defined filters are impossible to use.

**Comment by NO-ob** [comment]
Will be fixed in the next update, I might add filter selection for booru configs in the future also
