### ISSUE TITLE
[Bug] Hydrus Add A Tag Doesn't Add In The Comma

### ISSUE THREAD

**Issue by seniorm0ment** [NO-ob/LoliSnatcher_Droid#52]
When you run a search, click a file, view it's tags, then click add tag to pend it to your search, it doesn't add it with a comma when in Hydrus mode. So you have to manually add it.

Also worth noting, the dev has added an option for the user to choose whether they want to use underscores or spaces, that being said I believe it is still experimental and I'm not sure if it has been extended to the client api yet. Just worth noting, as it will eventually probably be something needing to be changed.

**Comment by NO-ob** [comment]
Fixed in next version
