### ISSUE TITLE
Client API with https incompatible with Hydrus booru api access

### ISSUE THREAD

**Issue by Spongiforma** [NO-ob/LoliSnatcher_Droid#61]
When running a hydrus client api with https enabled, Lolisnatcher does not seem to be able to perform api requests likely due to a self-signed SSL certificate warning. HTTP works however. It might be worth at least informing the user of the issue if not verifying the SSL certificate poses a risk.

**Comment by NO-ob** [comment]
Will fix this before next update

**Comment by NO-ob** [comment]
Have added a debug option in new app version to allow unsigned certs, its in the debug menu which can be accessed after tapping on the build number at the bottom of the settings page a few times
