### ISSUE TITLE
Cannot add furry.booru.org?

### ISSUE THREAD

**Issue by ZutgKcjA** [NO-ob/LoliSnatcher_Droid#63]
Hey, can someone help me understand how to add furry.booru.org to the list of boorus? It is supposedly running Gelbooru v0.2. Here are relevant links: 

- https://furry.booru.org/
- https://furry.booru.org/index.php?page=help&topic=dapi
- https://furry.booru.org/index.php?page=dapi&s=post&q=index

The app tells me "No data returned" no matter what I try.

**Comment by NANI-SORE** [comment]
It seems that they use cloudflare ddos protection which blocks app's requests. Try using VPNs, they could help with bypassing it.

**Comment by ZutgKcjA** [comment]
Alright thanks.
