### ISSUE TITLE
[Feature request] support to download images directly to Sd card

### ISSUE THREAD

**Issue by Losvayne** [NO-ob/LoliSnatcher_Droid#66]
I am running on android 7 (lenovo tab 4 8")

**Comment by Losvayne** [comment]
Whenever I try changing the storage directory of app to Sd card , it just shows 'directory not writable'or somethin'.

**Comment by NO-ob** [comment]
Its hard to do as I have no device with sd for testing, will be able to do it when I can get saf working i think
