### ISSUE TITLE
[Bug] I can't log in to Inkbunny with my credentials

### ISSUE THREAD

**Issue by ZutgKcjA** [NO-ob/LoliSnatcher_Droid#68]
I have tried to add Inkbunny as a source using my credentials. I get the "No data returned" error message. 
I can successfully add Inkbunny when I leave API key and User ID blank, but then the images I can view are limited, of course. 
I have tried several things, like switching around the user name and password between the two fields. 

Before you ask, I have activated API access in my Inkbunny settings and I have also used another tool that requires Inkbunny API access successfully using my credentials (IBDL).

I can't get it to work. My password contains special characters (such as # and !), could that be the cause?

**Comment by NO-ob** [comment]
Yeah its special chars in password. will be fixed in next update but for now you can change your pass
