### ISSUE TITLE
Autocomplete on paheal

### ISSUE THREAD

**Issue by NANI-SORE** [NO-ob/LoliSnatcher_Droid#7]
Add autocomplete for paheal
Example of paheal's autocomplete api url:
rule34.paheal.net/api/internal/autocomplete?s=tag_here&limit=5

It's probably paheal's exclusive plugin and won't work with other shimmie type sites

**Comment by grravity** [comment]
Can confirm, I cannot add Rule34 Paheal and it doesn't autocomplete

**Comment by NO-ob** [comment]
I should have free time in a week or so so will add support then

**Comment by NO-ob** [comment]
Added
