### ISSUE TITLE
[Bug] Unable to transfer favourites to other phone

### ISSUE THREAD

**Issue by makoto-kokoroki** [NO-ob/LoliSnatcher_Droid#77]
I am using a Galaxy Z Fold 3 and I am unable to send it my favorites, but, all my other imports have no issues.

**Comment by NO-ob** [comment]
Could you get logcats of both your devices please, Youll need adb on your computer if you dont.

Go on the app on both phones goto settings tap the version number at the bottom a few times. The debug settings should then appear. In there goto logger and turn all the options on

Plug the first phone into your pc and then do adb logcat  > logcat.txt and start a sync
After its failed plug the second device in and make another logcat and then try and sync again

**Comment by makoto-kokoroki** [comment]
Okay I enabled those settings, but, I am confused; do I need to use adb to get the logcat file or can I do that with just the settings enabled inside the debug options within lolisnatcher?

**Comment by makoto-kokoroki** [comment]
Okay I have no idea what I am doing in regards to this simple task. I believe I have all the necessary things set up in order for me to pull the logcat files. But I am not even a novice with any programming language... So bear with me here on getting this to you in a timely fashion.

**Comment by NO-ob** [comment]
I'd recommend installing minimal adb if youre on windows https://forum.xda-developers.com/t/tool-minimal-adb-and-fastboot-2-9-18.2317790/
