### ISSUE TITLE
Can't save selected booru to launch at start

### ISSUE THREAD

**Issue by ChillHorse** [NO-ob/LoliSnatcher_Droid#8]
When choosing to load another booru at start. The setting will not be rembered.
The saving toast does appear but it doesn't save. 
Currently 4 boorus are added on my device (Xperia 5, Android 10) rule33, gelbooru, danbooru, moebooru; with rule33 always as default no matter what I safe

**Comment by grravity** [comment]
Can confirm

**Comment by NO-ob** [comment]
I should have free time in a week or so so will look into this I must have broken it at some point lel

**Comment by NO-ob** [comment]
Actually im not sure I even added a feature to change the default booru, it uses the first one loaded from the config files, i'm not sure if its based on file creation date or modified date, for a temporary fix you could try editing the rule33 file and changing the contents of the file to the booru you want loaded first and renaming it, this wont work if it is loading is based on last modified date though.

**Comment by ChillHorse** [comment]
> Actually im not sure I even added a feature to change the default boor

well since the settings page for adding boorus as well as for overall settings is the same, I do thought it would let you save the start up booru after go through the dropdown/overlay and press save after your choice

**Comment by NO-ob** [comment]
Yeah I will add it its a good idea for a feature it just doesn't do that atm lel

**Comment by NO-ob** [comment]
Added
