### ISSUE TITLE
[Bug] Error in some e621 videos

### ISSUE THREAD

**Issue by Teramanbr** [NO-ob/LoliSnatcher_Droid#82]
Error when trying to see certain e621 videos.
Happens to me frequently.
![Screenshot_20220104-183831](https://user-images.githubusercontent.com/71410827/148286281-4cb14322-2ad3-467f-8000-0248b5f80509.png)

**Comment by NANI-SORE** [comment]
Can you give examples and/or search query you used?
That 404 error probably means that api somehow gave incorrect url or something else broke that url
