### ISSUE TITLE
Backup/Restore doesnt work on Android 11

### ISSUE THREAD

**Issue by aknight2015** [NO-ob/LoliSnatcher_Droid#83]
It all gets wiped out durring uninstall since I can't choose where it gets saved to.

**Comment by NANI-SORE** [comment]
For now you need to manually copy the backup files from /Android/data/*\*package_name\**/files (if default file manager doesn't allow that, use third-party app for that) and then return them back when the app is reinstalled.
Later we'll add file picker to restore from/save to any folder
