### ISSUE TITLE
[Bug] IdolSankaku shows a 'Error 500'

### ISSUE THREAD

**Issue by fartonicogames** [NO-ob/LoliSnatcher_Droid#85]
![Screenshot_105](https://user-images.githubusercontent.com/97577921/149067924-994df8d0-30ae-4b40-8ea9-00c4bafe57bb.png)
I'm just adding idol complex to search for some sauces and it gave this error screen, even searching the error screen appears too.

**Comment by NANI-SORE** [comment]
Works fine for me.
500 usually means that it's something broken on their end. Can you access it through browser?
You can try using vpn, but it probably won't help in this case.

**Comment by fartonicogames** [comment]
Works fine in browser, and trying to use a vpn to bypass i recieve a handshake error.

**Comment by NANI-SORE** [comment]
1. Try opening this link on the same device: https://iapi.sankakucomplex.com/post/index.json?tags=&limit=20&page=1
2. Try allowing self signed certificates in debug settings (tap app version a few times to show the button for them), probably won't work, but worth a try.

**Comment by fartonicogames** [comment]
I just tried step 1, it gave error 500 too
And now when I went to try step 2 it seems that the sankaku server doesn't work anymore
Maybe later the sankakucomplex come back with the server and i'll try

**Comment by NANI-SORE** [comment]
Server works right now for me. 
Since the direct api link also gives you 500, you are probably either region locked or ip banned by them

**Comment by fartonicogames** [comment]
Strange that sankaku complex api works, why sankaku idol is giving these errors

**Comment by NANI-SORE** [comment]
Maybe you triggered something on their end, they are known for having shitty rate limits. Though it is strange if they don't share bans between chan/idol.
We can't really do anything to circumvent the server error, aside from adding custom proxy

**Comment by fartonicogames** [comment]
I think my ip was banned from the site because it takes time to respond, I don't know which is the best vpn to get around this situation
