### ISSUE TITLE
[Bug] Gelbooru not showing tag suggestions

### ISSUE THREAD

**Issue by chocolate-neko** [NO-ob/LoliSnatcher_Droid#86]
Gelbooru is not showing any tag suggestions no matter what's being typed in the search box.
![Gelbooru](https://user-images.githubusercontent.com/44422224/149169560-ef0115c3-f2cc-4a27-8b5e-ce34e838b93f.jpg)

This was what previous behavior was meant to be like (using konachan as an example)
![Konachan](https://user-images.githubusercontent.com/44422224/149169899-07139a66-9357-4a62-8c17-cb15dc87c5ad.jpg)

Not sure if this is a bug or not, but thought I'd raise it up.

**Comment by NANI-SORE** [comment]
Yeah, It's broken.
Not sure if it happened today/yesterday or at the same time as the other breaking api change they did.
Will be fixed in the next release
