### ISSUE TITLE
[Bug & Request] Video Audio Plays After Swiping To Next & Autoplay Video

### ISSUE THREAD

**Issue by grravity** [NO-ob/LoliSnatcher_Droid#9]
When in slide view, videos with audio when played, then you swipe to the next, the audio is still stuck playing until that video finishes.

Also wanted to suggest ability for autoplaying videos.

**Comment by NO-ob** [comment]
I should have free time in a week or so will look into this then, i'm not sure if I could get auto play to work due to having multiple pages load at once so if I did add it it might have to only be enabled if preload is set to 0

**Comment by grravity** [comment]
Would it not make sense to load the pages seperately?
Like it loads the pages for indexing where you are and what's available, but when you click on something it loads the file directly?

I wonder if this is why some of the files seemed to be very low quality sometimes?

**Comment by NANI-SORE** [comment]
@NO-ob I was messing around with the code to add support for some noname sites
And also added third-party wrapper to enable video controls, autoplay and looping + fixed some bugs

I think I messed up some files when creating android studio project, idk, will look later and try to send pull request

**Comment by NO-ob** [comment]
Awesome thanks for working on some stuff, if its not building there may be files which needs manually changing im pretty sure I had to mess around with the android manifest xml files and build.gradle aswell but dont remember what ive changed maybe if you put yours on pastebin or something I can check whats different on my local copy

**Comment by NANI-SORE** [comment]
@NO-ob I sent a pull request with all changes

**Comment by NO-ob** [comment]
Thanks for helping out would you like your name added into the about page?

**Comment by NANI-SORE** [comment]
No problem, glad to help. You can add me, sure.

Will try to contribute more when I'll have some free time.
