### ISSUE TITLE
Yande.re Saving issues

### ISSUE THREAD

**Issue by MrInkless** [NO-ob/LoliSnatcher_Droid#95]
Yande.re has saving issues. Sometimes it will save the file, but will save it as "Yande_yande.jpeg (11)" or the file will just not save. If it does the former, the file name will need to be fixed by removing the (11) at the end.

I have reinstalled the app already. Note 10 Plus.

**Comment by NO-ob** [comment]
i'm 100% not sure what could be causing this it could be the special characters in the filenames maybe that causes issues with android 11 saving. i'll change the filenames in next release maybe that will fix it

**Comment by MrInkless** [comment]
I think I found maybe a temporary solution that may further help you figure out what is causing this issue.

Cause: I had changed the default save location to my default Pictures folder. This was causing the above issue

Temporary solution: Reset defaults on save location which would have LoliSnatcher create a specific folder on my phone for Yande.re specifically. I then move the photos to my Pictures folder. It asks me to rename the files because all of them are saving as "Yande_Yande.jpg".

Currently the last file I have moved over got renamed to "Yande_yande (8)(6).jpg". 

It seems it is not giving the photos the file names from yande, but just giving the title "Yande_yande.jpg" to each and every photo so they are not unique

**Comment by NO-ob** [comment]
Is this fixed in the newest release?

**Comment by MrInkless** [comment]
Issue has been resolved. Yande is now saving with the image names! Thank you for the fix so quickly!

**Comment by NO-ob** [comment]
I am having trouble reproducing this is it only yandere?
