### ISSUE TITLE
[Bug] Realbooru doesn't load videos

### ISSUE THREAD

**Issue by Vulldozer** [NO-ob/LoliSnatcher_Droid#98]
Realbooru used to work fine a few weeks ago but one day it just stopped loading videos, it can only load images.

The videos indefinitely buffer and there are no signs of progress.

I don't think it was broken by a LoliSnatcher update but rather something on realbooru's side broke.

**Comment by MajinSaaY** [comment]
Same here, maybe it's a problem with the website. This error occurs on other booru apps too.

**Comment by NO-ob** [comment]
will be fixed on next release
