### ISSUE TITLE
Improve default audio toggle / settings

### ISSUE THREAD

**Issue by daephx** [NO-ob/LoliSnatcher_Droid#99]
Referencing #48: Personally, I think a better solution to holding the speaker icon would be one click: on or off, toggling a global muted state for the whole gallery instead of having file dependent states. 

Also, when you boot up the app you could have videos start muted for safety (Assuming auto play is enabled).
Or you could add another toggle setting such as `Settings > Gallery > Start Videos muted` somewhere next to `Disable auto play`?

Other apps I've used that do this are, Sankaku's app, Clover / Kuroba.

**Comment by NANI-SORE** [comment]
Added mute setting in 2.4.0, didn't change global mute toggle though, I'll rework it in the new player
